# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

highlighter:         pygments

# Setup
title:               Nitin Martolia 
tagline:             'Blog for things I learn'
url:                 http://nitinmartolia.github.io
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Nitin Martolia
  url:               https://twitter.com/Nitin_Martolia
  email:             nitinmartolia@gmail.com

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/nitinmartolia/nitinmartolia.github.io
